version: '3'

services:
  db:
    image: mdillon/postgis:9.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: npm run dev -- --address=0.0.0.0 --port=8000
    environment:
      DJANGO_SETTINGS_MODULE: traffic_stops.settings.local
      PGDATABASE: traffic_stops
      PGUSER: postgres
      PGHOST: db
      DATABASE_URL: postgis://postgres@db:5432/traffic_stops
      DATABASE_URL_NC: postgis://postgres@db:5432/traffic_stops_nc
      DATABASE_URL_MD: postgis://postgres@db:5432/traffic_stops_md
      DATABASE_URL_IL: postgis://postgres@db:5432/traffic_stops_il
      VIRTUAL_ENV: /usr/local  # gulpfile expects Python to be in a virtualenv
    volumes:
      # mount local repository into the container
      - .:/code:delegated
      # If the developer wants to deploy inside a docker container, expose their
      # SSH keys to the container:
      - ~/.ssh:/root/.ssh
    ports:
      - "8003:8000"
    depends_on:
      - db

volumes:
  pgdata:
